### PR TITLE
Added sequence A001622

### LINKED ISSUE #59: Implement A001622
Doing it... Again.

### PR DESCRIPTION
**Pull request by valugit**
closes #59

### CODE REVIEW

**Comment by JulienPalard** [comment]
I wrote this test:
```python
@given(integers(min_value=0, max_value=2000))
def test_A001622(limit):
    assert A001622(limit=limit + 1)[:-1] == A001622(limit=limit)
```

to check decimals precision, and it fails:

```
Falsifying example: test_A001622(limit=375)
Traceback (most recent call last):
  File "/home/mdk/clones/JulienPalard/oeis/tests/test_A001622.py", line 8, in test_A001622
    assert A001622(limit=limit + 1)[:-1] == A001622(limit=limit)
AssertionError: assert [1, 6, 1, 8, 0, 3, ...] == [1, 6, 1, 8, 0, 3, ...]
  At index 374 diff: 4 != 5
  Use -v to get the full diff
```

**Comment by JulienPalard** [comment]
Interestingly, as travis is slower, the failure comes from the hypothesis deadline but not from a difference in results.

Your could lower the limit to around 400, as I'm seeing the bug at 375 already. I'm hitting deadline also, for `limit=1406`.

It can be reproduced easily:

```
$ python oeis.py A001622 --limit 376 --start 370 --limit 5
# A001622

Decimal expansion of golden ratio phi (or tau) = (1 + sqrt(5))/2.

[4, 6, 0, 7, 5]
$ python oeis.py A001622 --limit 376 --start 370 --limit 6
# A001622

Decimal expansion of golden ratio phi (or tau) = (1 + sqrt(5))/2.

[4, 6, 0, 7, 4, 9]
```

**Comment by JulienPalard** [comment]
I tried blindly with a `ctx.prec = start + limit + 3`, and I can't make it break, even by pushing the max_value to `4000` and the deadline to 10s.

It would be nice to set a hard limit on the implementations, like raising a ValueError if someone asks for `python oeis.py A001622 --start 1000000  --limit 1000010`. We know we can't answer this with the current algorithm, better raising than trying and failing.

The ValueError could be catched by the `main()` to nicely print a message on `stderr` about why we won't try to compute this. I bet many other implementations could add such a `raise`, but let's not do it in this unrelated PR.

**Comment by valugit** [comment]
I updated tests and change the precision to `ctx.prec = start + limit + 4`. It's seems to work properly now ...?

**Comment by JulienPalard** [comment]
It was not an easy one, nice!

**Pull request merged**
