### PR TITLE
A001221

### PR DESCRIPTION
**Pull request by eliott02022000**

### CODE REVIEW

**Comment by JulienPalard** [comment]
Beware, `flake8 tests/ oeis.py` gives:

    oeis.py:15:1: F811 redefinition of unused 'primefactors' from line 11

**Comment by JulienPalard** [comment]
Problem is funny: travis is trying on a merge of your branch and master, so travis sees:

```
*   3df9553 (HEAD) Merge 369f453414456c17fa8725294c755e43043ed911 into 7cbc92577babb8cf8defc170242721a8116eac90 2019-12-23 19:22:51 +0100 KingZayro
|\
| * 369f453 (eliott02022000/New-A001221, New-A001221) blackk 2019-12-23 19:22:42 +0100 Eliott
| * b76988e black 2019-12-23 19:17:27 +0100 Eliott
| * 6597f47 first commit 2019-12-23 19:07:32 +0100 Eliott
* | 7cbc925 Bump numpy from 1.17.4 to 1.18.0 (#105) 2019-12-23 17:19:16 +0100 dependabot-preview[bot]
* | 26bdab3 Bump hypothesis from 4.56.1 to 4.56.3 (#106) 2019-12-23 17:18:37 +0100 dependabot-preview[bot]
* | f15808d Bump mypy from 0.760 to 0.761 (#103) 2019-12-21 16:10:18 +0100 dependabot-preview[bot]
* | a6c4d8f Bump hypothesis from 4.55.2 to 4.56.1 (#102) 2019-12-21 15:31:21 +0100 dependabot-preview[bot]
* | 8c0d658 Bump hypothesis from 4.55.1 to 4.55.2 (#99) 2019-12-18 07:38:02 +0100 dependabot-preview[bot]
* | 81df9fe Bump mypy from 0.750 to 0.760 (#100) 2019-12-18 07:37:24 +0100 dependabot-preview[bot]
* | 2179ff2 Bump hypothesis from 4.54.0 to 4.55.1 (#98) 2019-12-18 00:39:59 +0100 dependabot-preview[bot]
* | 0493a3c Bump hypothesis from 4.53.2 to 4.54.0 (#97) 2019-12-16 09:17:04 +0100 dependabot-preview[bot]
* | c64f616 (origin/master, master) Bump sympy from 1.4 to 1.5 (#96) 2019-12-16 09:16:31 +0100 dependabot-preview[bot]
```

But in this "version" of the code there's two imports of `primefactors`:
```python
"""Tool that return a given sequence
"""
import argparse
from random import choice
import math
from math import factorial
from decimal import Decimal, localcontext
from typing import Collection, Dict, List, Callable
import sys
import os
from sympy import primefactors
from functools import reduce

import numpy as np
from sympy.ntheory import primefactors
import matplotlib.pyplot as plt


__version__ = "0.0.1"
```

You can easily resolve this by doing the merge yourself, fixing it, and pushing again, like:

```bash
$ git fetch upstream
$ git merge upstream/master
$ # fix the double import
$ git push
```

**Comment by eliott02022000** [comment]
thanks

> Problem is funny: travis is trying on a merge of your branch and master, so travis sees:
> 
> ```
> *   3df9553 (HEAD) Merge 369f453414456c17fa8725294c755e43043ed911 into 7cbc92577babb8cf8defc170242721a8116eac90 2019-12-23 19:22:51 +0100 KingZayro
> |\
> | * 369f453 (eliott02022000/New-A001221, New-A001221) blackk 2019-12-23 19:22:42 +0100 Eliott
> | * b76988e black 2019-12-23 19:17:27 +0100 Eliott
> | * 6597f47 first commit 2019-12-23 19:07:32 +0100 Eliott
> * | 7cbc925 Bump numpy from 1.17.4 to 1.18.0 (#105) 2019-12-23 17:19:16 +0100 dependabot-preview[bot]
> * | 26bdab3 Bump hypothesis from 4.56.1 to 4.56.3 (#106) 2019-12-23 17:18:37 +0100 dependabot-preview[bot]
> * | f15808d Bump mypy from 0.760 to 0.761 (#103) 2019-12-21 16:10:18 +0100 dependabot-preview[bot]
> * | a6c4d8f Bump hypothesis from 4.55.2 to 4.56.1 (#102) 2019-12-21 15:31:21 +0100 dependabot-preview[bot]
> * | 8c0d658 Bump hypothesis from 4.55.1 to 4.55.2 (#99) 2019-12-18 07:38:02 +0100 dependabot-preview[bot]
> * | 81df9fe Bump mypy from 0.750 to 0.760 (#100) 2019-12-18 07:37:24 +0100 dependabot-preview[bot]
> * | 2179ff2 Bump hypothesis from 4.54.0 to 4.55.1 (#98) 2019-12-18 00:39:59 +0100 dependabot-preview[bot]
> * | 0493a3c Bump hypothesis from 4.53.2 to 4.54.0 (#97) 2019-12-16 09:17:04 +0100 dependabot-preview[bot]
> * | c64f616 (origin/master, master) Bump sympy from 1.4 to 1.5 (#96) 2019-12-16 09:16:31 +0100 dependabot-preview[bot]
> ```
> 
> But in this "version" of the code there's two imports of `primefactors`:
> 
> ```python
> """Tool that return a given sequence
> """
> import argparse
> from random import choice
> import math
> from math import factorial
> from decimal import Decimal, localcontext
> from typing import Collection, Dict, List, Callable
> import sys
> import os
> from sympy import primefactors
> from functools import reduce
> 
> import numpy as np
> from sympy.ntheory import primefactors
> import matplotlib.pyplot as plt
> 
> 
> __version__ = "0.0.1"
> ```
> 
> You can easily resolve this by doing the merge yourself, fixing it, and pushing again, like:
> 
> ```shell
> $ git fetch upstream
> $ git merge upstream/master
> $ # fix the double import
> $ git push
> ```

thanks

**Comment by JulienPalard** [comment]
:+1:

**Pull request merged**
