### PR TITLE
Add A000032 (Lucas numbers)

### LINKED ISSUE #382: Implement A000032
Lucas numbers.

### PR DESCRIPTION
**Pull request by rwnobrega**
Fixes #382.

### CODE REVIEW

**Comment by JulienPalard** [comment]
I'd love to see this tested with hypothesis, something like:

```python
from hypothesis import given
from hypothesis.strategies import integers

@given(integers(min_value=2))
def test_A000032_definition(a):
    assert A000032[a] == A000032[a - 1] + A000032[a - 2]
```

if you go this way you could simplify the other test to only the two first values, like:

```python
def test_A000032_head():
    assert A000032[0] == 1
    assert A000032[1] == 2
```

the combination of the two tests **are** the definition of the serie, meaning:

- `A000032[0] == 1`
- `A000032[1] == 2`
- `A000032[a] == A000032[a - 1] + A000032[a - 2]`

and having the definition of the serie tested in the tests looks of good value to me :)

(But yes I do agree that your current combination of implementation and test are already robust enough.)

**Comment by rwnobrega** [comment]
Thank you!  I added the tests you proposed.  I kept the original test (now redundant) as `test_A000032_first_values`; for some reason it makes me feel safer.  But I can remove it if you want.

**Review by JulienPalard — APPROVED** [review]

**Comment by JulienPalard** [comment]
It looks good to me :)

**Comment by JulienPalard** [comment]
Thanks for the PR \o/

**Pull request merged**
