### PR TITLE
implemented A007947 & tests

### LINKED ISSUE #78: Implement A007947
Largest squarefree number dividing n: the squarefree kernel of n, rad(n), radical of n.

I'm doing it.

### PR DESCRIPTION
**Pull request by Aelyce11**
closes #78

### CODE REVIEW

**Comment by JulienPalard** [comment]
Did you forget to run `tox -p auto` before commiting?

**Comment by JulienPalard** [comment]
I would appreciate a test based on the definition of the sequence, I mean something like:
```python
@given(lists(primes())
def test_A007947(primes):
    composite = reduce(mul, primes, 1)
    expected = reduce(mul, set(primes), 1)
    assert A007947(composite, limit=1) == [expected]
```

Sadly there's no `prime()` strategy in hypothesis, maybe you can [adapt](https://hypothesis.readthedocs.io/en/latest/data.html#adapting-strategies) or [composite](https://hypothesis.readthedocs.io/en/latest/data.html#composite-strategies) one.

**Comment by Aelyce11** [comment]
I used `A000040` to get prime numbers since I think that's what you wanted with `primes()`, I'm not really sure if I got this right but the tests pass so tell me if this needs more editing.

**Comment by JulienPalard** [comment]
It's a really nice implementation, nice work, thanks!

**Pull request merged**
